[package]
name = "dependent_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curry-macro = "0.1.0"
dyn-clone = "1.0.16"
pest = "2.7.5"
pest_derive = "2.7.5"
